---
all:
  vars:
    env: local
    build_directory: "/Users/chloecorfmat/Documents/AE/Dev/chloecorfmat/ansible/build"
    deploy_directory: "/Users/chloecorfmat/Documents/AE/Dev/chloecorfmat/ansible/deploy"
    backups_directory: "/Users/chloecorfmat/Documents/AE/Dev/chloecorfmat/ansible/backups"
    DB:
      USER: ''
      PASSWORD: ''
      NAME: ''
      ROOT_PASSWORD: ''
  children:
    build:
      hosts:
        build:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    server:
      hosts:
        server:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3